In [1]:
"""Input & Output with console"""

# input 은 data 를 저장할 변수에 prompt 와 같이 쓴다
name = input("What's your name? ")
print("stored name is: ", name)

What's your name? inhan
stored name is:  inhan

In [7]:
# input 받은 data 는 언제나 string 이다.
value1 = input("Enter first number: ")
value2 = input("Enter second number: ")
value3 = value1 + value2
print(value1, value2, value3)
print(type(value1), type(value2), type(value3))

# 숫자로 쓰려면 type 변환을 해야한다.
value4 = int(value1) + int(value2)
print(value1, value2, value3, value4)
print(type(value1), type(value2), type(value3), type(value4))

Enter first number: 6
Enter second number: 7
6 7 67
<class 'str'> <class 'str'> <class 'str'>
6 7 67 13
<class 'str'> <class 'str'> <class 'str'> <class 'int'>

In [3]:
# 받을때부터 숫자로 받는법.
value5 = int(input("Enter first number: "))
value6 = int(input("Enter second number: "))
value7 = value5 + value6
print(value5, value6, value7)
print(type(value5), type(value6), type(value7))

Enter first number: 5
Enter second number: 6
5 6 11
<class 'int'> <class 'int'> <class 'int'>

In [ ]:
# single- 과 double- quoted string 모두 print 가능
print('Welcome to Python!')
print("Welcome to Python!")

Welcome to Python!
Welcome to Python!

In [ ]:
# comma 로 분리된 string
print('Welcome', 'to', 'Python!')

Welcome to Python!

In [ ]:
# Escape sequence 로 print
print('Welcome\nto\n\nPython!') # '\n' 은 next line
print('Welcome\tto\t\tPython!') # '\t' 은 tab
print('Welcome\\to\\Python!') # '\\' 은 '\' 표시
print('Welcome\'to\' \"Python!\"') # '\'' 은 ''' , '\"' 은 '"'

Welcome
to

Python!
Welcome	to		Python!
Welcome\to\Python!
Welcome'to' "Python!"

In [ ]:
# 긴라인을 표시하는 방법. 한줄로 나타남
print('this is a longer string, so we \
split it over two lines')

this is a longer string, so we split it over two lines

In [ ]:
# String 과 숫자를 표시하는 방법. 그냥 나열하면 됨
a = 3
print('Sum is', 7 + a, '변수 a 는 ', a)

Sum is 10 변수 a 는  3